// <auto-generated />
using HLTV_API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HLTV_API.Migrations
{
    [DbContext(typeof(HltvContext))]
    [Migration("20240204202815_BasicGuildEntity")]
    partial class BasicGuildEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HLTV_API.Domain.Guild", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LiveMatchAlertChannelId")
                        .HasColumnType("longtext");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
